#!/usr/bin/perl
# Finalise XSLT produced vertical file with UD annotations:
# - remove namespaces
# - de escape XML entities
# - remove leading and trailing spaces in values
# - cut too long positional attributes
# - add Slovene MSD
# - make lempos from lemma
use warnings;
use utf8;

#Maximum length of positional attribute
$maxlength = 200;

binmode STDERR, 'utf8';
binmode STDIN, 'utf8';
binmode STDOUT, 'utf8';

while (<DATA>) {
    chomp;
    my ($msd_en, $msd_sl) = split;
    $msd_en2sl{$msd_en} = $msd_sl;
}
while (<>) {
    chomp;
    #Get rid of namespaces
    s|(<.+?) xmlns(:.*?)?=".*?"|$1|;
    s|&apos;|'|g;
    s|&amp;|&|g;
    s|&quot;|"|g;
    if (/\t/) {
	$line = &fix_line($_);
	chomp;
	my ($word, $lemma, $msd_en,
	    $ud_pos, $ud_feats, $id, $ud_dep, 
	    $head_lemma, $head_msd_en,
	    $head_ud_pos, $head_ud_feats, $head_id) =
	    split(/\t/, $line);
	die "Bad MSD $msd_en in $_\n" unless exists $msd_en2sl{$msd_en};
	$msd_sl = $msd_en2sl{$msd_en};
	if ($head_msd_en eq '-') {$head_msd_sl = '-'}
	elsif (not exists $msd_en2sl{$head_msd_en}) {
	    die "Bad head MSD $head_msd_en in $_\n"
	}
	else {
	    $head_msd_sl = $msd_en2sl{$head_msd_en}
	}
	($msd_pos) = $msd_sl =~ /(.)/;
	$lempos = $lemma . '-' . lc($msd_pos);
	print join("\t", $word, $lempos, $msd_en, $msd_sl,
		   $ud_pos, $ud_feats, $id, $ud_dep, 
		   $head_lemma, $head_msd_en, $head_msd_sl,
		   $head_ud_pos, $head_ud_feats, $head_id) . "\n"
    }
    elsif (m|<[^/]|) {
	$line = fix_element($_);
	print "$line\n";
    }
    else {
	# De-escape in attribute values
	s|&lt;|<|g;
	s|&gt;|>|g;
	print;
	print "\n";
    }
}
sub fix_element {
    $in = shift;
    my $out;
    if ($in =~ s|\s\s+| |g) {
	print STDERR "WARN: removed multiple blanks from $in\n"
    }
    if ($in =~ s|= *" |="|g) {
	print STDERR "WARN: removed leading blank from $in\n"
    }
    if ($in =~ s| " |" |g) {
	print STDERR "WARN: removed trailing blank from $in\n"
    }
    if ($in =~ s| ">|">|) {
	print STDERR "WARN: removed trailing blank from $in\n"
    }
    $out = $in;
    return $out;
}
    
sub fix_line {
    my $in = shift;
    my @out;
    foreach my $str (split(/\t/, $in)) {
	$str =~ s|&lt;|<|g;
	$str =~ s|&gt;|>|g;
	$str =~ s|&quot;|"|g;
	if (length($str) > $maxlength) {
	    $str = substr($str, 1, $maxlength);
	    print STDERR "WARN: cut too long positional attribute in \n$in\n";
	}
	if ($str =~ s|\s\s+| |g) {
	    print STDERR "WARN: removed multiple blanks from $str in $in\n"
	}
	if ($str =~ s|^ ||) {
	    print STDERR "WARN: removed leading blank from $str in $in\n"
	}
	if ($str =~ s| $||) {
	    print STDERR "WARN: removed trailing blank from $str in $in\n"
	}
	push(@out, $str);
    }
    return join("\t", @out);
}

__DATA__
Ncmsn	Somei
Ncmsg	Somer
Ncmsd	Somed
Ncmsan	Sometn
Ncmsay	Sometd
Ncmsl	Somem
Ncmsi	Someo
Ncmdn	Somdi
Ncmdg	Somdr
Ncmdd	Somdd
Ncmda	Somdt
Ncmdl	Somdm
Ncmdi	Somdo
Ncmpn	Sommi
Ncmpg	Sommr
Ncmpd	Sommd
Ncmpa	Sommt
Ncmpl	Sommm
Ncmpi	Sommo
Ncfsn	Sozei
Ncfsg	Sozer
Ncfsd	Sozed
Ncfsa	Sozet
Ncfsl	Sozem
Ncfsi	Sozeo
Ncfdn	Sozdi
Ncfdg	Sozdr
Ncfdd	Sozdd
Ncfda	Sozdt
Ncfdl	Sozdm
Ncfdi	Sozdo
Ncfpn	Sozmi
Ncfpg	Sozmr
Ncfpd	Sozmd
Ncfpa	Sozmt
Ncfpl	Sozmm
Ncfpi	Sozmo
Ncnsn	Sosei
Ncnsg	Soser
Ncnsd	Sosed
Ncnsa	Soset
Ncnsl	Sosem
Ncnsi	Soseo
Ncndn	Sosdi
Ncndg	Sosdr
Ncndd	Sosdd
Ncnda	Sosdt
Ncndl	Sosdm
Ncndi	Sosdo
Ncnpn	Sosmi
Ncnpg	Sosmr
Ncnpd	Sosmd
Ncnpa	Sosmt
Ncnpl	Sosmm
Ncnpi	Sosmo
Npmsn	Slmei
Npmsg	Slmer
Npmsd	Slmed
Npmsan	Slmetn
Npmsay	Slmetd
Npmsl	Slmem
Npmsi	Slmeo
Npmdn	Slmdi
Npmdg	Slmdr
Npmdd	Slmdd
Npmda	Slmdt
Npmdl	Slmdm
Npmdi	Slmdo
Npmpn	Slmmi
Npmpg	Slmmr
Npmpd	Slmmd
Npmpa	Slmmt
Npmpl	Slmmm
Npmpi	Slmmo
Npfsn	Slzei
Npfsg	Slzer
Npfsd	Slzed
Npfsa	Slzet
Npfsl	Slzem
Npfsi	Slzeo
Npfdn	Slzdi
Npfdg	Slzdr
Npfdd	Slzdd
Npfda	Slzdt
Npfdl	Slzdm
Npfdi	Slzdo
Npfpn	Slzmi
Npfpg	Slzmr
Npfpd	Slzmd
Npfpa	Slzmt
Npfpl	Slzmm
Npfpi	Slzmo
Npnsn	Slsei
Npnsg	Slser
Npnsd	Slsed
Npnsa	Slset
Npnsl	Slsem
Npnsi	Slseo
Npnpn	Slsmi
Npnpg	Slsmr
Npnpd	Slsmd
Npnpa	Slsmt
Npnpl	Slsmm
Npnpi	Slsmo
Vmen	Ggdn
Vmeu	Ggdm
Vmep-sm	Ggdd-em
Vmep-sf	Ggdd-ez
Vmep-sn	Ggdd-es
Vmep-pm	Ggdd-mm
Vmep-pf	Ggdd-mz
Vmep-pn	Ggdd-ms
Vmep-dm	Ggdd-dm
Vmep-df	Ggdd-dz
Vmep-dn	Ggdd-ds
Vmer1s	Ggdspe
Vmer1p	Ggdspm
Vmer1d	Ggdspd
Vmer2s	Ggdsde
Vmer2p	Ggdsdm
Vmer2d	Ggdsdd
Vmer3s	Ggdste
Vmer3p	Ggdstm
Vmer3d	Ggdstd
Vmem1p	Ggdvpm
Vmem1d	Ggdvpd
Vmem2s	Ggdvde
Vmem2p	Ggdvdm
Vmem2d	Ggdvdd
Vmpn	Ggnn
Vmpu	Ggnm
Vmpp-sm	Ggnd-em
Vmpp-sf	Ggnd-ez
Vmpp-sn	Ggnd-es
Vmpp-pm	Ggnd-mm
Vmpp-pf	Ggnd-mz
Vmpp-pn	Ggnd-ms
Vmpp-dm	Ggnd-dm
Vmpp-df	Ggnd-dz
Vmpp-dn	Ggnd-ds
Vmpr1s	Ggnspe
Vmpr1s-n	Ggnspe-n
Vmpr1s-y	Ggnspe-d
Vmpr1p	Ggnspm
Vmpr1p-n	Ggnspm-n
Vmpr1p-y	Ggnspm-d
Vmpr1d	Ggnspd
Vmpr1d-n	Ggnspd-n
Vmpr1d-y	Ggnspd-d
Vmpr2s	Ggnsde
Vmpr2s-n	Ggnsde-n
Vmpr2s-y	Ggnsde-d
Vmpr2p	Ggnsdm
Vmpr2p-n	Ggnsdm-n
Vmpr2p-y	Ggnsdm-d
Vmpr2d	Ggnsdd
Vmpr2d-n	Ggnsdd-n
Vmpr2d-y	Ggnsdd-d
Vmpr3s	Ggnste
Vmpr3s-n	Ggnste-n
Vmpr3s-y	Ggnste-d
Vmpr3p	Ggnstm
Vmpr3p-n	Ggnstm-n
Vmpr3p-y	Ggnstm-d
Vmpr3d	Ggnstd
Vmpr3d-n	Ggnstd-n
Vmpr3d-y	Ggnstd-d
Vmpm1p	Ggnvpm
Vmpm1d	Ggnvpd
Vmpm2s	Ggnvde
Vmpm2p	Ggnvdm
Vmpm2d	Ggnvdd
Vmbn	Ggvn
Vmbu	Ggvm
Vmbp-sm	Ggvd-em
Vmbp-sf	Ggvd-ez
Vmbp-sn	Ggvd-es
Vmbp-pm	Ggvd-mm
Vmbp-pf	Ggvd-mz
Vmbp-pn	Ggvd-ms
Vmbp-dm	Ggvd-dm
Vmbp-df	Ggvd-dz
Vmbp-dn	Ggvd-ds
Vmbr1s	Ggvspe
Vmbr1p	Ggvspm
Vmbr1d	Ggvspd
Vmbr1df	Ggvspdz
Vmbr2s	Ggvsde
Vmbr2p	Ggvsdm
Vmbr2d	Ggvsdd
Vmbr3s	Ggvste
Vmbr3p	Ggvstm
Vmbr3d	Ggvstd
Vmbf1s	Ggvppe
Vmbf1p	Ggvppm
Vmbf1d	Ggvppd
Vmbf2s	Ggvpde
Vmbf2p	Ggvpdm
Vmbf2d	Ggvpdd
Vmbf3s	Ggvpte
Vmbf3p	Ggvptm
Vmbf3d	Ggvptd
Vmbm1p	Ggvvpm
Vmbm1d	Ggvvpd
Vmbm2s	Ggvvde
Vmbm2p	Ggvvdm
Vmbm2d	Ggvvdd
Va-n	Gp-n
Va-u	Gp-m
Va-p-sm	Gp-d-em
Va-p-sf	Gp-d-ez
Va-p-sn	Gp-d-es
Va-p-pm	Gp-d-mm
Va-p-pf	Gp-d-mz
Va-p-pn	Gp-d-ms
Va-p-dm	Gp-d-dm
Va-p-df	Gp-d-dz
Va-p-dn	Gp-d-ds
Va-r1s-n	Gp-spe-n
Va-r1s-y	Gp-spe-d
Va-r1p-n	Gp-spm-n
Va-r1p-y	Gp-spm-d
Va-r1d-n	Gp-spd-n
Va-r1d-y	Gp-spd-d
Va-r1dfn	Gp-spdzn
Va-r2s-n	Gp-sde-n
Va-r2s-y	Gp-sde-d
Va-r2p-n	Gp-sdm-n
Va-r2p-y	Gp-sdm-d
Va-r2d-n	Gp-sdd-n
Va-r2d-y	Gp-sdd-d
Va-r3s-n	Gp-ste-n
Va-r3s-y	Gp-ste-d
Va-r3p-n	Gp-stm-n
Va-r3p-y	Gp-stm-d
Va-r3d-n	Gp-std-n
Va-r3d-y	Gp-std-d
Va-f1s-n	Gp-ppe-n
Va-f1s-y	Gp-ppe-d
Va-f1p-n	Gp-ppm-n
Va-f1p-y	Gp-ppm-d
Va-f1d	Gp-ppd
Va-f1d-n	Gp-ppd-n
Va-f1d-y	Gp-ppd-d
Va-f2s-n	Gp-pde-n
Va-f2s-y	Gp-pde-d
Va-f2p-n	Gp-pdm-n
Va-f2d-n	Gp-pdd-n
Va-f3s-n	Gp-pte-n
Va-f3s-y	Gp-pte-d
Va-f3p-n	Gp-ptm-n
Va-f3p-y	Gp-ptm-d
Va-f3d-n	Gp-ptd-n
Va-c	Gp-g
Va-c---y	Gp-g---d
Va-m1p	Gp-vpm
Va-m1d	Gp-vpd
Va-m2s	Gp-vde
Va-m2p	Gp-vdm
Va-m2d	Gp-vdd
Agpmsnn	Ppnmein
Agpmsny	Ppnmeid
Agpmsg	Ppnmer
Agpmsd	Ppnmed
Agpmsa	Ppnmet
Agpmsan	Ppnmetn
Agpmsay	Ppnmetd
Agpmsl	Ppnmem
Agpmsi	Ppnmeo
Agpmdn	Ppnmdi
Agpmdg	Ppnmdr
Agpmdd	Ppnmdd
Agpmda	Ppnmdt
Agpmdl	Ppnmdm
Agpmdi	Ppnmdo
Agpmpn	Ppnmmi
Agpmpg	Ppnmmr
Agpmpd	Ppnmmd
Agpmpa	Ppnmmt
Agpmpl	Ppnmmm
Agpmpi	Ppnmmo
Agpfsn	Ppnzei
Agpfsg	Ppnzer
Agpfsd	Ppnzed
Agpfsa	Ppnzet
Agpfsl	Ppnzem
Agpfsi	Ppnzeo
Agpfdn	Ppnzdi
Agpfdg	Ppnzdr
Agpfdd	Ppnzdd
Agpfda	Ppnzdt
Agpfdl	Ppnzdm
Agpfdi	Ppnzdo
Agpfpn	Ppnzmi
Agpfpg	Ppnzmr
Agpfpd	Ppnzmd
Agpfpa	Ppnzmt
Agpfpl	Ppnzmm
Agpfpi	Ppnzmo
Agpnsn	Ppnsei
Agpnsg	Ppnser
Agpnsd	Ppnsed
Agpnsa	Ppnset
Agpnsl	Ppnsem
Agpnsi	Ppnseo
Agpndn	Ppnsdi
Agpndg	Ppnsdr
Agpndd	Ppnsdd
Agpnda	Ppnsdt
Agpndl	Ppnsdm
Agpndi	Ppnsdo
Agpnpn	Ppnsmi
Agpnpg	Ppnsmr
Agpnpd	Ppnsmd
Agpnpa	Ppnsmt
Agpnpl	Ppnsmm
Agpnpi	Ppnsmo
Agcmsny	Pppmeid
Agcmsg	Pppmer
Agcmsd	Pppmed
Agcmsa	Pppmet
Agcmsay	Pppmetd
Agcmsl	Pppmem
Agcmsi	Pppmeo
Agcmdn	Pppmdi
Agcmdg	Pppmdr
Agcmdd	Pppmdd
Agcmda	Pppmdt
Agcmdl	Pppmdm
Agcmdi	Pppmdo
Agcmpn	Pppmmi
Agcmpg	Pppmmr
Agcmpd	Pppmmd
Agcmpa	Pppmmt
Agcmpl	Pppmmm
Agcmpi	Pppmmo
Agcfsn	Pppzei
Agcfsg	Pppzer
Agcfsd	Pppzed
Agcfsa	Pppzet
Agcfsl	Pppzem
Agcfsi	Pppzeo
Agcfdn	Pppzdi
Agcfdg	Pppzdr
Agcfdd	Pppzdd
Agcfda	Pppzdt
Agcfdl	Pppzdm
Agcfdi	Pppzdo
Agcfpn	Pppzmi
Agcfpg	Pppzmr
Agcfpd	Pppzmd
Agcfpa	Pppzmt
Agcfpl	Pppzmm
Agcfpi	Pppzmo
Agcnsn	Pppsei
Agcnsg	Pppser
Agcnsd	Pppsed
Agcnsa	Pppset
Agcnsl	Pppsem
Agcnsi	Pppseo
Agcndn	Pppsdi
Agcndg	Pppsdr
Agcndd	Pppsdd
Agcnda	Pppsdt
Agcndl	Pppsdm
Agcndi	Pppsdo
Agcnpn	Pppsmi
Agcnpg	Pppsmr
Agcnpd	Pppsmd
Agcnpa	Pppsmt
Agcnpl	Pppsmm
Agcnpi	Pppsmo
Agsmsny	Ppsmeid
Agsmsg	Ppsmer
Agsmsd	Ppsmed
Agsmsa	Ppsmet
Agsmsay	Ppsmetd
Agsmsl	Ppsmem
Agsmsi	Ppsmeo
Agsmdn	Ppsmdi
Agsmdg	Ppsmdr
Agsmdd	Ppsmdd
Agsmda	Ppsmdt
Agsmdl	Ppsmdm
Agsmdi	Ppsmdo
Agsmpn	Ppsmmi
Agsmpg	Ppsmmr
Agsmpd	Ppsmmd
Agsmpa	Ppsmmt
Agsmpl	Ppsmmm
Agsmpi	Ppsmmo
Agsfsn	Ppszei
Agsfsg	Ppszer
Agsfsd	Ppszed
Agsfsa	Ppszet
Agsfsl	Ppszem
Agsfsi	Ppszeo
Agsfdn	Ppszdi
Agsfdg	Ppszdr
Agsfdd	Ppszdd
Agsfda	Ppszdt
Agsfdl	Ppszdm
Agsfdi	Ppszdo
Agsfpn	Ppszmi
Agsfpg	Ppszmr
Agsfpd	Ppszmd
Agsfpa	Ppszmt
Agsfpl	Ppszmm
Agsfpi	Ppszmo
Agsnsn	Ppssei
Agsnsg	Ppsser
Agsnsd	Ppssed
Agsnsa	Ppsset
Agsnsl	Ppssem
Agsnsi	Ppsseo
Agsndn	Ppssdi
Agsndg	Ppssdr
Agsndd	Ppssdd
Agsnda	Ppssdt
Agsndl	Ppssdm
Agsndi	Ppssdo
Agsnpn	Ppssmi
Agsnpg	Ppssmr
Agsnpd	Ppssmd
Agsnpa	Ppssmt
Agsnpl	Ppssmm
Agsnpi	Ppssmo
Aspmsnn	Psnmein
Aspmsg	Psnmer
Aspmsd	Psnmed
Aspmsa	Psnmet
Aspmsan	Psnmetn
Aspmsl	Psnmem
Aspmsi	Psnmeo
Aspmdn	Psnmdi
Aspmdg	Psnmdr
Aspmdd	Psnmdd
Aspmda	Psnmdt
Aspmdl	Psnmdm
Aspmdi	Psnmdo
Aspmpn	Psnmmi
Aspmpg	Psnmmr
Aspmpd	Psnmmd
Aspmpa	Psnmmt
Aspmpl	Psnmmm
Aspmpi	Psnmmo
Aspfsn	Psnzei
Aspfsg	Psnzer
Aspfsd	Psnzed
Aspfsa	Psnzet
Aspfsl	Psnzem
Aspfsi	Psnzeo
Aspfdn	Psnzdi
Aspfdg	Psnzdr
Aspfdd	Psnzdd
Aspfda	Psnzdt
Aspfdl	Psnzdm
Aspfdi	Psnzdo
Aspfpn	Psnzmi
Aspfpg	Psnzmr
Aspfpd	Psnzmd
Aspfpa	Psnzmt
Aspfpl	Psnzmm
Aspfpi	Psnzmo
Aspnsn	Psnsei
Aspnsg	Psnser
Aspnsd	Psnsed
Aspnsa	Psnset
Aspnsl	Psnsem
Aspnsi	Psnseo
Aspndn	Psnsdi
Aspndg	Psnsdr
Aspndd	Psnsdd
Aspnda	Psnsdt
Aspndl	Psnsdm
Aspndi	Psnsdo
Aspnpn	Psnsmi
Aspnpg	Psnsmr
Aspnpd	Psnsmd
Aspnpa	Psnsmt
Aspnpl	Psnsmm
Aspnpi	Psnsmo
Appmsnn	Pdnmein
Appmsny	Pdnmeid
Appmsg	Pdnmer
Appmsd	Pdnmed
Appmsa	Pdnmet
Appmsan	Pdnmetn
Appmsay	Pdnmetd
Appmsl	Pdnmem
Appmsi	Pdnmeo
Appmdn	Pdnmdi
Appmdg	Pdnmdr
Appmdd	Pdnmdd
Appmda	Pdnmdt
Appmdl	Pdnmdm
Appmdi	Pdnmdo
Appmpn	Pdnmmi
Appmpg	Pdnmmr
Appmpd	Pdnmmd
Appmpa	Pdnmmt
Appmpl	Pdnmmm
Appmpi	Pdnmmo
Appfsn	Pdnzei
Appfsg	Pdnzer
Appfsd	Pdnzed
Appfsa	Pdnzet
Appfsl	Pdnzem
Appfsi	Pdnzeo
Appfdn	Pdnzdi
Appfdg	Pdnzdr
Appfdd	Pdnzdd
Appfda	Pdnzdt
Appfdl	Pdnzdm
Appfdi	Pdnzdo
Appfpn	Pdnzmi
Appfpg	Pdnzmr
Appfpd	Pdnzmd
Appfpa	Pdnzmt
Appfpl	Pdnzmm
Appfpi	Pdnzmo
Appnsn	Pdnsei
Appnsg	Pdnser
Appnsd	Pdnsed
Appnsa	Pdnset
Appnsl	Pdnsem
Appnsi	Pdnseo
Appndn	Pdnsdi
Appndg	Pdnsdr
Appndd	Pdnsdd
Appnda	Pdnsdt
Appndl	Pdnsdm
Appndi	Pdnsdo
Appnpn	Pdnsmi
Appnpg	Pdnsmr
Appnpd	Pdnsmd
Appnpa	Pdnsmt
Appnpl	Pdnsmm
Appnpi	Pdnsmo
Rgp	Rsn
Rgc	Rsr
Rgs	Rss
Rr	Rd
Pp1-sn	Zop-ei
Pp1-sg	Zop-er
Pp1-sg--y	Zop-er--k
Pp1-sd	Zop-ed
Pp1-sd--y	Zop-ed--k
Pp1-sa	Zop-et
Pp1-sa--y	Zop-et--k
Pp1-sa--b	Zop-et--z
Pp1-sl	Zop-em
Pp1-si	Zop-eo
Pp1-dg	Zop-dr
Pp1-dd	Zop-dd
Pp1-da	Zop-dt
Pp1-dl	Zop-dm
Pp1-di	Zop-do
Pp1-pg	Zop-mr
Pp1-pd	Zop-md
Pp1-pa	Zop-mt
Pp1-pl	Zop-mm
Pp1-pi	Zop-mo
Pp1mdn	Zopmdi
Pp1mpn	Zopmmi
Pp1fdn	Zopzdi
Pp1fpn	Zopzmi
Pp2-sn	Zod-ei
Pp2-sg	Zod-er
Pp2-sg--y	Zod-er--k
Pp2-sd	Zod-ed
Pp2-sd--y	Zod-ed--k
Pp2-sa	Zod-et
Pp2-sa--y	Zod-et--k
Pp2-sa--b	Zod-et--z
Pp2-sl	Zod-em
Pp2-si	Zod-eo
Pp2-dg	Zod-dr
Pp2-dd	Zod-dd
Pp2-da	Zod-dt
Pp2-dl	Zod-dm
Pp2-di	Zod-do
Pp2-pg	Zod-mr
Pp2-pd	Zod-md
Pp2-pa	Zod-mt
Pp2-pl	Zod-mm
Pp2-pi	Zod-mo
Pp2mdn	Zodmdi
Pp2mpn	Zodmmi
Pp2fdn	Zodzdi
Pp2fpn	Zodzmi
Pp2ndn	Zodsdi
Pp2npn	Zodsmi
Pp3msn	Zotmei
Pp3msg	Zotmer
Pp3msg--y	Zotmer--k
Pp3msd	Zotmed
Pp3msd--y	Zotmed--k
Pp3msa	Zotmet
Pp3msa--y	Zotmet--k
Pp3msa--b	Zotmet--z
Pp3msl	Zotmem
Pp3msi	Zotmeo
Pp3mdn	Zotmdi
Pp3mdg	Zotmdr
Pp3mdg--y	Zotmdr--k
Pp3mdd	Zotmdd
Pp3mdd--y	Zotmdd--k
Pp3mda	Zotmdt
Pp3mda--y	Zotmdt--k
Pp3mda--b	Zotmdt--z
Pp3mdl	Zotmdm
Pp3mdi	Zotmdo
Pp3mpn	Zotmmi
Pp3mpg	Zotmmr
Pp3mpg--y	Zotmmr--k
Pp3mpd	Zotmmd
Pp3mpd--y	Zotmmd--k
Pp3mpa	Zotmmt
Pp3mpa--y	Zotmmt--k
Pp3mpa--b	Zotmmt--z
Pp3mpl	Zotmmm
Pp3mpi	Zotmmo
Pp3fsn	Zotzei
Pp3fsg	Zotzer
Pp3fsg--y	Zotzer--k
Pp3fsd	Zotzed
Pp3fsd--y	Zotzed--k
Pp3fsa	Zotzet
Pp3fsa--y	Zotzet--k
Pp3fsa--b	Zotzet--z
Pp3fsl	Zotzem
Pp3fsi	Zotzeo
Pp3fdn	Zotzdi
Pp3fdg	Zotzdr
Pp3fdg--y	Zotzdr--k
Pp3fdd	Zotzdd
Pp3fdd--y	Zotzdd--k
Pp3fda	Zotzdt
Pp3fda--y	Zotzdt--k
Pp3fda--b	Zotzdt--z
Pp3fdl	Zotzdm
Pp3fdi	Zotzdo
Pp3fpn	Zotzmi
Pp3fpg	Zotzmr
Pp3fpg--y	Zotzmr--k
Pp3fpd	Zotzmd
Pp3fpd--y	Zotzmd--k
Pp3fpa	Zotzmt
Pp3fpa--y	Zotzmt--k
Pp3fpa--b	Zotzmt--z
Pp3fpl	Zotzmm
Pp3fpi	Zotzmo
Pp3nsn	Zotsei
Pp3nsg	Zotser
Pp3nsg--y	Zotser--k
Pp3nsd	Zotsed
Pp3nsd--y	Zotsed--k
Pp3nsa	Zotset
Pp3nsa--y	Zotset--k
Pp3nsa--b	Zotset--z
Pp3nsl	Zotsem
Pp3nsi	Zotseo
Pp3ndn	Zotsdi
Pp3ndg	Zotsdr
Pp3ndg--y	Zotsdr--k
Pp3ndd	Zotsdd
Pp3ndd--y	Zotsdd--k
Pp3nda	Zotsdt
Pp3nda--y	Zotsdt--k
Pp3nda--b	Zotsdt--z
Pp3ndl	Zotsdm
Pp3ndi	Zotsdo
Pp3npn	Zotsmi
Pp3npg	Zotsmr
Pp3npg--y	Zotsmr--k
Pp3npd	Zotsmd
Pp3npd--y	Zotsmd--k
Pp3npa	Zotsmt
Pp3npa--y	Zotsmt--k
Pp3npa--b	Zotsmt--z
Pp3npl	Zotsmm
Pp3npi	Zotsmo
Ps1msns	Zspmeie
Ps1msnd	Zspmeid
Ps1msnp	Zspmeim
Ps1msgs	Zspmere
Ps1msgd	Zspmerd
Ps1msgp	Zspmerm
Ps1msds	Zspmede
Ps1msdd	Zspmedd
Ps1msdp	Zspmedm
Ps1msas	Zspmete
Ps1msad	Zspmetd
Ps1msap	Zspmetm
Ps1msls	Zspmeme
Ps1msld	Zspmemd
Ps1mslp	Zspmemm
Ps1msis	Zspmeoe
Ps1msid	Zspmeod
Ps1msip	Zspmeom
Ps1mdns	Zspmdie
Ps1mdnd	Zspmdid
Ps1mdnp	Zspmdim
Ps1mdgs	Zspmdre
Ps1mdgd	Zspmdrd
Ps1mdgp	Zspmdrm
Ps1mdds	Zspmdde
Ps1mddd	Zspmddd
Ps1mddp	Zspmddm
Ps1mdas	Zspmdte
Ps1mdad	Zspmdtd
Ps1mdap	Zspmdtm
Ps1mdls	Zspmdme
Ps1mdld	Zspmdmd
Ps1mdlp	Zspmdmm
Ps1mdis	Zspmdoe
Ps1mdid	Zspmdod
Ps1mdip	Zspmdom
Ps1mpns	Zspmmie
Ps1mpnd	Zspmmid
Ps1mpnp	Zspmmim
Ps1mpgs	Zspmmre
Ps1mpgd	Zspmmrd
Ps1mpgp	Zspmmrm
Ps1mpds	Zspmmde
Ps1mpdd	Zspmmdd
Ps1mpdp	Zspmmdm
Ps1mpas	Zspmmte
Ps1mpad	Zspmmtd
Ps1mpap	Zspmmtm
Ps1mpls	Zspmmme
Ps1mpld	Zspmmmd
Ps1mplp	Zspmmmm
Ps1mpis	Zspmmoe
Ps1mpid	Zspmmod
Ps1mpip	Zspmmom
Ps1fsns	Zspzeie
Ps1fsnd	Zspzeid
Ps1fsnp	Zspzeim
Ps1fsgs	Zspzere
Ps1fsgd	Zspzerd
Ps1fsgp	Zspzerm
Ps1fsds	Zspzede
Ps1fsdd	Zspzedd
Ps1fsdp	Zspzedm
Ps1fsas	Zspzete
Ps1fsad	Zspzetd
Ps1fsap	Zspzetm
Ps1fsls	Zspzeme
Ps1fsld	Zspzemd
Ps1fslp	Zspzemm
Ps1fsis	Zspzeoe
Ps1fsid	Zspzeod
Ps1fsip	Zspzeom
Ps1fdns	Zspzdie
Ps1fdnd	Zspzdid
Ps1fdnp	Zspzdim
Ps1fdgs	Zspzdre
Ps1fdgd	Zspzdrd
Ps1fdgp	Zspzdrm
Ps1fdds	Zspzdde
Ps1fddd	Zspzddd
Ps1fddp	Zspzddm
Ps1fdas	Zspzdte
Ps1fdad	Zspzdtd
Ps1fdap	Zspzdtm
Ps1fdls	Zspzdme
Ps1fdld	Zspzdmd
Ps1fdlp	Zspzdmm
Ps1fdis	Zspzdoe
Ps1fdid	Zspzdod
Ps1fdip	Zspzdom
Ps1fpns	Zspzmie
Ps1fpnd	Zspzmid
Ps1fpnp	Zspzmim
Ps1fpgs	Zspzmre
Ps1fpgd	Zspzmrd
Ps1fpgp	Zspzmrm
Ps1fpds	Zspzmde
Ps1fpdd	Zspzmdd
Ps1fpdp	Zspzmdm
Ps1fpas	Zspzmte
Ps1fpad	Zspzmtd
Ps1fpap	Zspzmtm
Ps1fpls	Zspzmme
Ps1fpld	Zspzmmd
Ps1fplp	Zspzmmm
Ps1fpis	Zspzmoe
Ps1fpid	Zspzmod
Ps1fpip	Zspzmom
Ps1nsns	Zspseie
Ps1nsnd	Zspseid
Ps1nsnp	Zspseim
Ps1nsgs	Zspsere
Ps1nsgd	Zspserd
Ps1nsgp	Zspserm
Ps1nsds	Zspsede
Ps1nsdd	Zspsedd
Ps1nsdp	Zspsedm
Ps1nsas	Zspsete
Ps1nsad	Zspsetd
Ps1nsap	Zspsetm
Ps1nsls	Zspseme
Ps1nsld	Zspsemd
Ps1nslp	Zspsemm
Ps1nsis	Zspseoe
Ps1nsid	Zspseod
Ps1nsip	Zspseom
Ps1ndns	Zspsdie
Ps1ndnd	Zspsdid
Ps1ndnp	Zspsdim
Ps1ndgs	Zspsdre
Ps1ndgd	Zspsdrd
Ps1ndgp	Zspsdrm
Ps1ndds	Zspsdde
Ps1nddd	Zspsddd
Ps1nddp	Zspsddm
Ps1ndas	Zspsdte
Ps1ndad	Zspsdtd
Ps1ndap	Zspsdtm
Ps1ndls	Zspsdme
Ps1ndld	Zspsdmd
Ps1ndlp	Zspsdmm
Ps1ndis	Zspsdoe
Ps1ndid	Zspsdod
Ps1ndip	Zspsdom
Ps1npns	Zspsmie
Ps1npnd	Zspsmid
Ps1npnp	Zspsmim
Ps1npgs	Zspsmre
Ps1npgd	Zspsmrd
Ps1npgp	Zspsmrm
Ps1npds	Zspsmde
Ps1npdd	Zspsmdd
Ps1npdp	Zspsmdm
Ps1npas	Zspsmte
Ps1npad	Zspsmtd
Ps1npap	Zspsmtm
Ps1npls	Zspsmme
Ps1npld	Zspsmmd
Ps1nplp	Zspsmmm
Ps1npis	Zspsmoe
Ps1npid	Zspsmod
Ps1npip	Zspsmom
Ps2msns	Zsdmeie
Ps2msnd	Zsdmeid
Ps2msnp	Zsdmeim
Ps2msgs	Zsdmere
Ps2msgd	Zsdmerd
Ps2msgp	Zsdmerm
Ps2msds	Zsdmede
Ps2msdd	Zsdmedd
Ps2msdp	Zsdmedm
Ps2msas	Zsdmete
Ps2msad	Zsdmetd
Ps2msap	Zsdmetm
Ps2msls	Zsdmeme
Ps2msld	Zsdmemd
Ps2mslp	Zsdmemm
Ps2msis	Zsdmeoe
Ps2msid	Zsdmeod
Ps2msip	Zsdmeom
Ps2mdns	Zsdmdie
Ps2mdnd	Zsdmdid
Ps2mdnp	Zsdmdim
Ps2mdgs	Zsdmdre
Ps2mdgd	Zsdmdrd
Ps2mdgp	Zsdmdrm
Ps2mdds	Zsdmdde
Ps2mddd	Zsdmddd
Ps2mddp	Zsdmddm
Ps2mdas	Zsdmdte
Ps2mdad	Zsdmdtd
Ps2mdap	Zsdmdtm
Ps2mdls	Zsdmdme
Ps2mdld	Zsdmdmd
Ps2mdlp	Zsdmdmm
Ps2mdis	Zsdmdoe
Ps2mdid	Zsdmdod
Ps2mdip	Zsdmdom
Ps2mpns	Zsdmmie
Ps2mpnd	Zsdmmid
Ps2mpnp	Zsdmmim
Ps2mpgs	Zsdmmre
Ps2mpgd	Zsdmmrd
Ps2mpgp	Zsdmmrm
Ps2mpds	Zsdmmde
Ps2mpdd	Zsdmmdd
Ps2mpdp	Zsdmmdm
Ps2mpas	Zsdmmte
Ps2mpad	Zsdmmtd
Ps2mpap	Zsdmmtm
Ps2mpls	Zsdmmme
Ps2mpld	Zsdmmmd
Ps2mplp	Zsdmmmm
Ps2mpis	Zsdmmoe
Ps2mpid	Zsdmmod
Ps2mpip	Zsdmmom
Ps2fsns	Zsdzeie
Ps2fsnd	Zsdzeid
Ps2fsnp	Zsdzeim
Ps2fsgs	Zsdzere
Ps2fsgd	Zsdzerd
Ps2fsgp	Zsdzerm
Ps2fsds	Zsdzede
Ps2fsdd	Zsdzedd
Ps2fsdp	Zsdzedm
Ps2fsas	Zsdzete
Ps2fsad	Zsdzetd
Ps2fsap	Zsdzetm
Ps2fsls	Zsdzeme
Ps2fsld	Zsdzemd
Ps2fslp	Zsdzemm
Ps2fsis	Zsdzeoe
Ps2fsid	Zsdzeod
Ps2fsip	Zsdzeom
Ps2fdns	Zsdzdie
Ps2fdnd	Zsdzdid
Ps2fdnp	Zsdzdim
Ps2fdgs	Zsdzdre
Ps2fdgd	Zsdzdrd
Ps2fdgp	Zsdzdrm
Ps2fdds	Zsdzdde
Ps2fddd	Zsdzddd
Ps2fddp	Zsdzddm
Ps2fdas	Zsdzdte
Ps2fdad	Zsdzdtd
Ps2fdap	Zsdzdtm
Ps2fdls	Zsdzdme
Ps2fdld	Zsdzdmd
Ps2fdlp	Zsdzdmm
Ps2fdis	Zsdzdoe
Ps2fdid	Zsdzdod
Ps2fdip	Zsdzdom
Ps2fpns	Zsdzmie
Ps2fpnd	Zsdzmid
Ps2fpnp	Zsdzmim
Ps2fpgs	Zsdzmre
Ps2fpgd	Zsdzmrd
Ps2fpgp	Zsdzmrm
Ps2fpds	Zsdzmde
Ps2fpdd	Zsdzmdd
Ps2fpdp	Zsdzmdm
Ps2fpas	Zsdzmte
Ps2fpad	Zsdzmtd
Ps2fpap	Zsdzmtm
Ps2fpls	Zsdzmme
Ps2fpld	Zsdzmmd
Ps2fplp	Zsdzmmm
Ps2fpis	Zsdzmoe
Ps2fpid	Zsdzmod
Ps2fpip	Zsdzmom
Ps2nsns	Zsdseie
Ps2nsnd	Zsdseid
Ps2nsnp	Zsdseim
Ps2nsgs	Zsdsere
Ps2nsgd	Zsdserd
Ps2nsgp	Zsdserm
Ps2nsds	Zsdsede
Ps2nsdd	Zsdsedd
Ps2nsdp	Zsdsedm
Ps2nsas	Zsdsete
Ps2nsad	Zsdsetd
Ps2nsap	Zsdsetm
Ps2nsls	Zsdseme
Ps2nsld	Zsdsemd
Ps2nslp	Zsdsemm
Ps2nsis	Zsdseoe
Ps2nsid	Zsdseod
Ps2nsip	Zsdseom
Ps2ndns	Zsdsdie
Ps2ndnd	Zsdsdid
Ps2ndnp	Zsdsdim
Ps2ndgs	Zsdsdre
Ps2ndgd	Zsdsdrd
Ps2ndgp	Zsdsdrm
Ps2ndds	Zsdsdde
Ps2nddd	Zsdsddd
Ps2nddp	Zsdsddm
Ps2ndas	Zsdsdte
Ps2ndad	Zsdsdtd
Ps2ndap	Zsdsdtm
Ps2ndls	Zsdsdme
Ps2ndld	Zsdsdmd
Ps2ndlp	Zsdsdmm
Ps2ndis	Zsdsdoe
Ps2ndid	Zsdsdod
Ps2ndip	Zsdsdom
Ps2npns	Zsdsmie
Ps2npnd	Zsdsmid
Ps2npnp	Zsdsmim
Ps2npgs	Zsdsmre
Ps2npgd	Zsdsmrd
Ps2npgp	Zsdsmrm
Ps2npds	Zsdsmde
Ps2npdd	Zsdsmdd
Ps2npdp	Zsdsmdm
Ps2npas	Zsdsmte
Ps2npad	Zsdsmtd
Ps2npap	Zsdsmtm
Ps2npls	Zsdsmme
Ps2npld	Zsdsmmd
Ps2nplp	Zsdsmmm
Ps2npis	Zsdsmoe
Ps2npid	Zsdsmod
Ps2npip	Zsdsmom
Ps3msnsm	Zstmeiem
Ps3msnsf	Zstmeiez
Ps3msnsn	Zstmeies
Ps3msnd	Zstmeid
Ps3msnp	Zstmeim
Ps3msgsm	Zstmerem
Ps3msgsf	Zstmerez
Ps3msgsn	Zstmeres
Ps3msgd	Zstmerd
Ps3msgp	Zstmerm
Ps3msdsm	Zstmedem
Ps3msdsf	Zstmedez
Ps3msdsn	Zstmedes
Ps3msdd	Zstmedd
Ps3msdp	Zstmedm
Ps3msasm	Zstmetem
Ps3msasf	Zstmetez
Ps3msasn	Zstmetes
Ps3msad	Zstmetd
Ps3msap	Zstmetm
Ps3mslsm	Zstmemem
Ps3mslsf	Zstmemez
Ps3mslsn	Zstmemes
Ps3msld	Zstmemd
Ps3mslp	Zstmemm
Ps3msism	Zstmeoem
Ps3msisf	Zstmeoez
Ps3msisn	Zstmeoes
Ps3msid	Zstmeod
Ps3msip	Zstmeom
Ps3mdnsm	Zstmdiem
Ps3mdnsf	Zstmdiez
Ps3mdnsn	Zstmdies
Ps3mdnd	Zstmdid
Ps3mdnp	Zstmdim
Ps3mdgsm	Zstmdrem
Ps3mdgsf	Zstmdrez
Ps3mdgsn	Zstmdres
Ps3mdgd	Zstmdrd
Ps3mdgp	Zstmdrm
Ps3mddsm	Zstmddem
Ps3mddsf	Zstmddez
Ps3mddsn	Zstmddes
Ps3mddd	Zstmddd
Ps3mddp	Zstmddm
Ps3mdasm	Zstmdtem
Ps3mdasf	Zstmdtez
Ps3mdasn	Zstmdtes
Ps3mdad	Zstmdtd
Ps3mdap	Zstmdtm
Ps3mdlsm	Zstmdmem
Ps3mdlsf	Zstmdmez
Ps3mdlsn	Zstmdmes
Ps3mdld	Zstmdmd
Ps3mdlp	Zstmdmm
Ps3mdism	Zstmdoem
Ps3mdisf	Zstmdoez
Ps3mdisn	Zstmdoes
Ps3mdid	Zstmdod
Ps3mdip	Zstmdom
Ps3mpnsm	Zstmmiem
Ps3mpnsf	Zstmmiez
Ps3mpnsn	Zstmmies
Ps3mpnd	Zstmmid
Ps3mpnp	Zstmmim
Ps3mpgsm	Zstmmrem
Ps3mpgsf	Zstmmrez
Ps3mpgsn	Zstmmres
Ps3mpgd	Zstmmrd
Ps3mpgp	Zstmmrm
Ps3mpdsm	Zstmmdem
Ps3mpdsf	Zstmmdez
Ps3mpdsn	Zstmmdes
Ps3mpdd	Zstmmdd
Ps3mpdp	Zstmmdm
Ps3mpasm	Zstmmtem
Ps3mpasf	Zstmmtez
Ps3mpasn	Zstmmtes
Ps3mpad	Zstmmtd
Ps3mpap	Zstmmtm
Ps3mplsm	Zstmmmem
Ps3mplsf	Zstmmmez
Ps3mplsn	Zstmmmes
Ps3mpld	Zstmmmd
Ps3mplp	Zstmmmm
Ps3mpism	Zstmmoem
Ps3mpisf	Zstmmoez
Ps3mpisn	Zstmmoes
Ps3mpid	Zstmmod
Ps3mpip	Zstmmom
Ps3fsnsm	Zstzeiem
Ps3fsnsf	Zstzeiez
Ps3fsnsn	Zstzeies
Ps3fsnd	Zstzeid
Ps3fsnp	Zstzeim
Ps3fsgsm	Zstzerem
Ps3fsgsf	Zstzerez
Ps3fsgsn	Zstzeres
Ps3fsgd	Zstzerd
Ps3fsgp	Zstzerm
Ps3fsdsm	Zstzedem
Ps3fsdsf	Zstzedez
Ps3fsdsn	Zstzedes
Ps3fsdd	Zstzedd
Ps3fsdp	Zstzedm
Ps3fsasm	Zstzetem
Ps3fsasf	Zstzetez
Ps3fsasn	Zstzetes
Ps3fsad	Zstzetd
Ps3fsap	Zstzetm
Ps3fslsm	Zstzemem
Ps3fslsf	Zstzemez
Ps3fslsn	Zstzemes
Ps3fsld	Zstzemd
Ps3fslp	Zstzemm
Ps3fsism	Zstzeoem
Ps3fsisf	Zstzeoez
Ps3fsisn	Zstzeoes
Ps3fsid	Zstzeod
Ps3fsip	Zstzeom
Ps3fdnsm	Zstzdiem
Ps3fdnsf	Zstzdiez
Ps3fdnsn	Zstzdies
Ps3fdnd	Zstzdid
Ps3fdnp	Zstzdim
Ps3fdgsm	Zstzdrem
Ps3fdgsf	Zstzdrez
Ps3fdgsn	Zstzdres
Ps3fdgd	Zstzdrd
Ps3fdgp	Zstzdrm
Ps3fddsm	Zstzddem
Ps3fddsf	Zstzddez
Ps3fddsn	Zstzddes
Ps3fddd	Zstzddd
Ps3fddp	Zstzddm
Ps3fdasm	Zstzdtem
Ps3fdasf	Zstzdtez
Ps3fdasn	Zstzdtes
Ps3fdad	Zstzdtd
Ps3fdap	Zstzdtm
Ps3fdlsm	Zstzdmem
Ps3fdlsf	Zstzdmez
Ps3fdlsn	Zstzdmes
Ps3fdld	Zstzdmd
Ps3fdlp	Zstzdmm
Ps3fdism	Zstzdoem
Ps3fdisf	Zstzdoez
Ps3fdisn	Zstzdoes
Ps3fdid	Zstzdod
Ps3fdip	Zstzdom
Ps3fpnsm	Zstzmiem
Ps3fpnsf	Zstzmiez
Ps3fpnsn	Zstzmies
Ps3fpnd	Zstzmid
Ps3fpnp	Zstzmim
Ps3fpgsm	Zstzmrem
Ps3fpgsf	Zstzmrez
Ps3fpgsn	Zstzmres
Ps3fpgd	Zstzmrd
Ps3fpgp	Zstzmrm
Ps3fpdsm	Zstzmdem
Ps3fpdsf	Zstzmdez
Ps3fpdsn	Zstzmdes
Ps3fpdd	Zstzmdd
Ps3fpdp	Zstzmdm
Ps3fpasm	Zstzmtem
Ps3fpasf	Zstzmtez
Ps3fpasn	Zstzmtes
Ps3fpad	Zstzmtd
Ps3fpap	Zstzmtm
Ps3fplsm	Zstzmmem
Ps3fplsf	Zstzmmez
Ps3fplsn	Zstzmmes
Ps3fpld	Zstzmmd
Ps3fplp	Zstzmmm
Ps3fpism	Zstzmoem
Ps3fpisf	Zstzmoez
Ps3fpisn	Zstzmoes
Ps3fpid	Zstzmod
Ps3fpip	Zstzmom
Ps3nsnsm	Zstseiem
Ps3nsnsf	Zstseiez
Ps3nsnsn	Zstseies
Ps3nsnd	Zstseid
Ps3nsnp	Zstseim
Ps3nsgsm	Zstserem
Ps3nsgsf	Zstserez
Ps3nsgsn	Zstseres
Ps3nsgd	Zstserd
Ps3nsgp	Zstserm
Ps3nsdsm	Zstsedem
Ps3nsdsf	Zstsedez
Ps3nsdsn	Zstsedes
Ps3nsdd	Zstsedd
Ps3nsdp	Zstsedm
Ps3nsasm	Zstsetem
Ps3nsasf	Zstsetez
Ps3nsasn	Zstsetes
Ps3nsad	Zstsetd
Ps3nsap	Zstsetm
Ps3nslsm	Zstsemem
Ps3nslsf	Zstsemez
Ps3nslsn	Zstsemes
Ps3nsld	Zstsemd
Ps3nslp	Zstsemm
Ps3nsism	Zstseoem
Ps3nsisf	Zstseoez
Ps3nsisn	Zstseoes
Ps3nsid	Zstseod
Ps3nsip	Zstseom
Ps3ndnsm	Zstsdiem
Ps3ndnsf	Zstsdiez
Ps3ndnsn	Zstsdies
Ps3ndnd	Zstsdid
Ps3ndnp	Zstsdim
Ps3ndgsm	Zstsdrem
Ps3ndgsf	Zstsdrez
Ps3ndgsn	Zstsdres
Ps3ndgd	Zstsdrd
Ps3ndgp	Zstsdrm
Ps3nddsm	Zstsddem
Ps3nddsf	Zstsddez
Ps3nddsn	Zstsddes
Ps3nddd	Zstsddd
Ps3nddp	Zstsddm
Ps3ndasm	Zstsdtem
Ps3ndasf	Zstsdtez
Ps3ndasn	Zstsdtes
Ps3ndad	Zstsdtd
Ps3ndap	Zstsdtm
Ps3ndlsm	Zstsdmem
Ps3ndlsf	Zstsdmez
Ps3ndlsn	Zstsdmes
Ps3ndld	Zstsdmd
Ps3ndlp	Zstsdmm
Ps3ndism	Zstsdoem
Ps3ndisf	Zstsdoez
Ps3ndisn	Zstsdoes
Ps3ndid	Zstsdod
Ps3ndip	Zstsdom
Ps3npnsm	Zstsmiem
Ps3npnsf	Zstsmiez
Ps3npnsn	Zstsmies
Ps3npnd	Zstsmid
Ps3npnp	Zstsmim
Ps3npgsm	Zstsmrem
Ps3npgsf	Zstsmrez
Ps3npgsn	Zstsmres
Ps3npgd	Zstsmrd
Ps3npgp	Zstsmrm
Ps3npdsm	Zstsmdem
Ps3npdsf	Zstsmdez
Ps3npdsn	Zstsmdes
Ps3npdd	Zstsmdd
Ps3npdp	Zstsmdm
Ps3npasm	Zstsmtem
Ps3npasf	Zstsmtez
Ps3npasn	Zstsmtes
Ps3npad	Zstsmtd
Ps3npap	Zstsmtm
Ps3nplsm	Zstsmmem
Ps3nplsf	Zstsmmez
Ps3nplsn	Zstsmmes
Ps3npld	Zstsmmd
Ps3nplp	Zstsmmm
Ps3npism	Zstsmoem
Ps3npisf	Zstsmoez
Ps3npisn	Zstsmoes
Ps3npid	Zstsmod
Ps3npip	Zstsmom
Pd-msn	Zk-mei
Pd-msg	Zk-mer
Pd-msd	Zk-med
Pd-msa	Zk-met
Pd-msl	Zk-mem
Pd-msi	Zk-meo
Pd-mdn	Zk-mdi
Pd-mdg	Zk-mdr
Pd-mdd	Zk-mdd
Pd-mda	Zk-mdt
Pd-mdl	Zk-mdm
Pd-mdi	Zk-mdo
Pd-mpn	Zk-mmi
Pd-mpg	Zk-mmr
Pd-mpd	Zk-mmd
Pd-mpa	Zk-mmt
Pd-mpl	Zk-mmm
Pd-mpi	Zk-mmo
Pd-fsn	Zk-zei
Pd-fsg	Zk-zer
Pd-fsd	Zk-zed
Pd-fsa	Zk-zet
Pd-fsl	Zk-zem
Pd-fsi	Zk-zeo
Pd-fdn	Zk-zdi
Pd-fdg	Zk-zdr
Pd-fdd	Zk-zdd
Pd-fda	Zk-zdt
Pd-fdl	Zk-zdm
Pd-fdi	Zk-zdo
Pd-fpn	Zk-zmi
Pd-fpg	Zk-zmr
Pd-fpd	Zk-zmd
Pd-fpa	Zk-zmt
Pd-fpl	Zk-zmm
Pd-fpi	Zk-zmo
Pd-nsn	Zk-sei
Pd-nsg	Zk-ser
Pd-nsd	Zk-sed
Pd-nsa	Zk-set
Pd-nsl	Zk-sem
Pd-nsi	Zk-seo
Pd-ndn	Zk-sdi
Pd-ndg	Zk-sdr
Pd-ndd	Zk-sdd
Pd-nda	Zk-sdt
Pd-ndl	Zk-sdm
Pd-ndi	Zk-sdo
Pd-npn	Zk-smi
Pd-npg	Zk-smr
Pd-npd	Zk-smd
Pd-npa	Zk-smt
Pd-npl	Zk-smm
Pd-npi	Zk-smo
Pr	Zz
Pr----sm	Zz----em
Pr-msn	Zz-mei
Pr-msg	Zz-mer
Pr-msd	Zz-med
Pr-msa	Zz-met
Pr-msl	Zz-mem
Pr-msi	Zz-meo
Pr-mdn	Zz-mdi
Pr-mdg	Zz-mdr
Pr-mdd	Zz-mdd
Pr-mda	Zz-mdt
Pr-mdl	Zz-mdm
Pr-mdi	Zz-mdo
Pr-mpn	Zz-mmi
Pr-mpg	Zz-mmr
Pr-mpd	Zz-mmd
Pr-mpa	Zz-mmt
Pr-mpl	Zz-mmm
Pr-mpi	Zz-mmo
Pr-fsn	Zz-zei
Pr-fsg	Zz-zer
Pr-fsd	Zz-zed
Pr-fsa	Zz-zet
Pr-fsl	Zz-zem
Pr-fsi	Zz-zeo
Pr-fdn	Zz-zdi
Pr-fdg	Zz-zdr
Pr-fdd	Zz-zdd
Pr-fda	Zz-zdt
Pr-fdl	Zz-zdm
Pr-fdi	Zz-zdo
Pr-fpn	Zz-zmi
Pr-fpg	Zz-zmr
Pr-fpd	Zz-zmd
Pr-fpa	Zz-zmt
Pr-fpl	Zz-zmm
Pr-fpi	Zz-zmo
Pr-nsn	Zz-sei
Pr-nsg	Zz-ser
Pr-nsd	Zz-sed
Pr-nsa	Zz-set
Pr-nsl	Zz-sem
Pr-nsi	Zz-seo
Pr-ndn	Zz-sdi
Pr-ndg	Zz-sdr
Pr-ndd	Zz-sdd
Pr-nda	Zz-sdt
Pr-ndl	Zz-sdm
Pr-ndi	Zz-sdo
Pr-npn	Zz-smi
Pr-npg	Zz-smr
Pr-npd	Zz-smd
Pr-npa	Zz-smt
Pr-npl	Zz-smm
Pr-npi	Zz-smo
Px------y	Zp------k
Px---g	Zp---r
Px---d	Zp---d
Px---d--y	Zp---d--k
Px---a	Zp---t
Px---a--b	Zp---t--z
Px---l	Zp---m
Px---i	Zp---o
Px-msn	Zp-mei
Px-msg	Zp-mer
Px-msd	Zp-med
Px-msa	Zp-met
Px-msl	Zp-mem
Px-msi	Zp-meo
Px-mdn	Zp-mdi
Px-mdg	Zp-mdr
Px-mdd	Zp-mdd
Px-mda	Zp-mdt
Px-mdl	Zp-mdm
Px-mdi	Zp-mdo
Px-mpn	Zp-mmi
Px-mpg	Zp-mmr
Px-mpd	Zp-mmd
Px-mpa	Zp-mmt
Px-mpl	Zp-mmm
Px-mpi	Zp-mmo
Px-fsn	Zp-zei
Px-fsg	Zp-zer
Px-fsd	Zp-zed
Px-fsa	Zp-zet
Px-fsl	Zp-zem
Px-fsi	Zp-zeo
Px-fdn	Zp-zdi
Px-fdg	Zp-zdr
Px-fdd	Zp-zdd
Px-fda	Zp-zdt
Px-fdl	Zp-zdm
Px-fdi	Zp-zdo
Px-fpn	Zp-zmi
Px-fpg	Zp-zmr
Px-fpd	Zp-zmd
Px-fpa	Zp-zmt
Px-fpl	Zp-zmm
Px-fpi	Zp-zmo
Px-nsn	Zp-sei
Px-nsg	Zp-ser
Px-nsd	Zp-sed
Px-nsa	Zp-set
Px-nsl	Zp-sem
Px-nsi	Zp-seo
Px-ndn	Zp-sdi
Px-ndg	Zp-sdr
Px-ndd	Zp-sdd
Px-nda	Zp-sdt
Px-ndl	Zp-sdm
Px-ndi	Zp-sdo
Px-npn	Zp-smi
Px-npg	Zp-smr
Px-npd	Zp-smd
Px-npa	Zp-smt
Px-npl	Zp-smm
Px-npi	Zp-smo
Pg-msn	Zc-mei
Pg-msg	Zc-mer
Pg-msd	Zc-med
Pg-msa	Zc-met
Pg-msl	Zc-mem
Pg-msi	Zc-meo
Pg-mdn	Zc-mdi
Pg-mdg	Zc-mdr
Pg-mdd	Zc-mdd
Pg-mda	Zc-mdt
Pg-mdl	Zc-mdm
Pg-mdi	Zc-mdo
Pg-mpn	Zc-mmi
Pg-mpg	Zc-mmr
Pg-mpd	Zc-mmd
Pg-mpa	Zc-mmt
Pg-mpl	Zc-mmm
Pg-mpi	Zc-mmo
Pg-fsn	Zc-zei
Pg-fsg	Zc-zer
Pg-fsd	Zc-zed
Pg-fsa	Zc-zet
Pg-fsl	Zc-zem
Pg-fsi	Zc-zeo
Pg-fdn	Zc-zdi
Pg-fdg	Zc-zdr
Pg-fdd	Zc-zdd
Pg-fda	Zc-zdt
Pg-fdl	Zc-zdm
Pg-fdi	Zc-zdo
Pg-fpn	Zc-zmi
Pg-fpg	Zc-zmr
Pg-fpd	Zc-zmd
Pg-fpa	Zc-zmt
Pg-fpl	Zc-zmm
Pg-fpi	Zc-zmo
Pg-nsn	Zc-sei
Pg-nsg	Zc-ser
Pg-nsd	Zc-sed
Pg-nsa	Zc-set
Pg-nsl	Zc-sem
Pg-nsi	Zc-seo
Pg-ndn	Zc-sdi
Pg-ndg	Zc-sdr
Pg-ndd	Zc-sdd
Pg-nda	Zc-sdt
Pg-ndl	Zc-sdm
Pg-ndi	Zc-sdo
Pg-npn	Zc-smi
Pg-npg	Zc-smr
Pg-npd	Zc-smd
Pg-npa	Zc-smt
Pg-npl	Zc-smm
Pg-npi	Zc-smo
Pq-msn	Zv-mei
Pq-msg	Zv-mer
Pq-msd	Zv-med
Pq-msa	Zv-met
Pq-msl	Zv-mem
Pq-msi	Zv-meo
Pq-mdn	Zv-mdi
Pq-mdg	Zv-mdr
Pq-mdd	Zv-mdd
Pq-mda	Zv-mdt
Pq-mdl	Zv-mdm
Pq-mdi	Zv-mdo
Pq-mpn	Zv-mmi
Pq-mpg	Zv-mmr
Pq-mpd	Zv-mmd
Pq-mpa	Zv-mmt
Pq-mpl	Zv-mmm
Pq-mpi	Zv-mmo
Pq-fsn	Zv-zei
Pq-fsg	Zv-zer
Pq-fsd	Zv-zed
Pq-fsa	Zv-zet
Pq-fsl	Zv-zem
Pq-fsi	Zv-zeo
Pq-fdn	Zv-zdi
Pq-fdg	Zv-zdr
Pq-fdd	Zv-zdd
Pq-fda	Zv-zdt
Pq-fdl	Zv-zdm
Pq-fdi	Zv-zdo
Pq-fpn	Zv-zmi
Pq-fpg	Zv-zmr
Pq-fpd	Zv-zmd
Pq-fpa	Zv-zmt
Pq-fpl	Zv-zmm
Pq-fpi	Zv-zmo
Pq-nsn	Zv-sei
Pq-nsg	Zv-ser
Pq-nsd	Zv-sed
Pq-nsa	Zv-set
Pq-nsl	Zv-sem
Pq-nsi	Zv-seo
Pq-ndn	Zv-sdi
Pq-ndg	Zv-sdr
Pq-ndd	Zv-sdd
Pq-nda	Zv-sdt
Pq-ndl	Zv-sdm
Pq-ndi	Zv-sdo
Pq-npn	Zv-smi
Pq-npg	Zv-smr
Pq-npd	Zv-smd
Pq-npa	Zv-smt
Pq-npl	Zv-smm
Pq-npi	Zv-smo
Pi-msn	Zn-mei
Pi-msg	Zn-mer
Pi-msd	Zn-med
Pi-msa	Zn-met
Pi-msl	Zn-mem
Pi-msi	Zn-meo
Pi-mdn	Zn-mdi
Pi-mdg	Zn-mdr
Pi-mdd	Zn-mdd
Pi-mda	Zn-mdt
Pi-mdl	Zn-mdm
Pi-mdi	Zn-mdo
Pi-mpn	Zn-mmi
Pi-mpg	Zn-mmr
Pi-mpd	Zn-mmd
Pi-mpa	Zn-mmt
Pi-mpl	Zn-mmm
Pi-mpi	Zn-mmo
Pi-fsn	Zn-zei
Pi-fsg	Zn-zer
Pi-fsd	Zn-zed
Pi-fsa	Zn-zet
Pi-fsl	Zn-zem
Pi-fsi	Zn-zeo
Pi-fdn	Zn-zdi
Pi-fdg	Zn-zdr
Pi-fdd	Zn-zdd
Pi-fda	Zn-zdt
Pi-fdl	Zn-zdm
Pi-fdi	Zn-zdo
Pi-fpn	Zn-zmi
Pi-fpg	Zn-zmr
Pi-fpd	Zn-zmd
Pi-fpa	Zn-zmt
Pi-fpl	Zn-zmm
Pi-fpi	Zn-zmo
Pi-nsn	Zn-sei
Pi-nsg	Zn-ser
Pi-nsd	Zn-sed
Pi-nsa	Zn-set
Pi-nsl	Zn-sem
Pi-nsi	Zn-seo
Pi-ndn	Zn-sdi
Pi-ndg	Zn-sdr
Pi-ndd	Zn-sdd
Pi-nda	Zn-sdt
Pi-ndl	Zn-sdm
Pi-ndi	Zn-sdo
Pi-npn	Zn-smi
Pi-npg	Zn-smr
Pi-npd	Zn-smd
Pi-npa	Zn-smt
Pi-npl	Zn-smm
Pi-npi	Zn-smo
Pz-msn	Zl-mei
Pz-msg	Zl-mer
Pz-msd	Zl-med
Pz-msa	Zl-met
Pz-msl	Zl-mem
Pz-msi	Zl-meo
Pz-mdn	Zl-mdi
Pz-mdg	Zl-mdr
Pz-mdd	Zl-mdd
Pz-mda	Zl-mdt
Pz-mdl	Zl-mdm
Pz-mdi	Zl-mdo
Pz-mpn	Zl-mmi
Pz-mpg	Zl-mmr
Pz-mpd	Zl-mmd
Pz-mpa	Zl-mmt
Pz-mpl	Zl-mmm
Pz-mpi	Zl-mmo
Pz-fsn	Zl-zei
Pz-fsg	Zl-zer
Pz-fsd	Zl-zed
Pz-fsa	Zl-zet
Pz-fsl	Zl-zem
Pz-fsi	Zl-zeo
Pz-fdn	Zl-zdi
Pz-fdg	Zl-zdr
Pz-fdd	Zl-zdd
Pz-fda	Zl-zdt
Pz-fdl	Zl-zdm
Pz-fdi	Zl-zdo
Pz-fpn	Zl-zmi
Pz-fpg	Zl-zmr
Pz-fpd	Zl-zmd
Pz-fpa	Zl-zmt
Pz-fpl	Zl-zmm
Pz-fpi	Zl-zmo
Pz-nsn	Zl-sei
Pz-nsg	Zl-ser
Pz-nsd	Zl-sed
Pz-nsa	Zl-set
Pz-nsl	Zl-sem
Pz-nsi	Zl-seo
Pz-ndn	Zl-sdi
Pz-ndg	Zl-sdr
Pz-ndd	Zl-sdd
Pz-nda	Zl-sdt
Pz-ndl	Zl-sdm
Pz-ndi	Zl-sdo
Pz-npn	Zl-smi
Pz-npg	Zl-smr
Pz-npd	Zl-smd
Pz-npa	Zl-smt
Pz-npl	Zl-smm
Pz-npi	Zl-smo
Mdc	Kag
Mdo	Kav
Mrc	Krg
Mro	Krv
Mlc-pn	Kbg-mi
Mlc-pg	Kbg-mr
Mlc-pd	Kbg-md
Mlc-pa	Kbg-mt
Mlc-pl	Kbg-mm
Mlc-pi	Kbg-mo
Mlcmdn	Kbgmdi
Mlcmdg	Kbgmdr
Mlcmdd	Kbgmdd
Mlcmda	Kbgmdt
Mlcmdl	Kbgmdm
Mlcmdi	Kbgmdo
Mlcmpn	Kbgmmi
Mlcmpg	Kbgmmr
Mlcmpd	Kbgmmd
Mlcmpa	Kbgmmt
Mlcmpl	Kbgmmm
Mlcmpi	Kbgmmo
Mlcfdn	Kbgzdi
Mlcfdg	Kbgzdr
Mlcfdd	Kbgzdd
Mlcfda	Kbgzdt
Mlcfdl	Kbgzdm
Mlcfdi	Kbgzdo
Mlcfpn	Kbgzmi
Mlcfpg	Kbgzmr
Mlcfpd	Kbgzmd
Mlcfpa	Kbgzmt
Mlcfpl	Kbgzmm
Mlcfpi	Kbgzmo
Mlcndn	Kbgsdi
Mlcndg	Kbgsdr
Mlcndd	Kbgsdd
Mlcnda	Kbgsdt
Mlcndl	Kbgsdm
Mlcndi	Kbgsdo
Mlcnpn	Kbgsmi
Mlcnpg	Kbgsmr
Mlcnpd	Kbgsmd
Mlcnpa	Kbgsmt
Mlcnpl	Kbgsmm
Mlcnpi	Kbgsmo
Mlomsn	Kbvmei
Mlomsg	Kbvmer
Mlomsd	Kbvmed
Mlomsa	Kbvmet
Mlomsl	Kbvmem
Mlomsi	Kbvmeo
Mlomdn	Kbvmdi
Mlomdg	Kbvmdr
Mlomdd	Kbvmdd
Mlomda	Kbvmdt
Mlomdl	Kbvmdm
Mlomdi	Kbvmdo
Mlompn	Kbvmmi
Mlompg	Kbvmmr
Mlompd	Kbvmmd
Mlompa	Kbvmmt
Mlompl	Kbvmmm
Mlompi	Kbvmmo
Mlofsn	Kbvzei
Mlofsg	Kbvzer
Mlofsd	Kbvzed
Mlofsa	Kbvzet
Mlofsl	Kbvzem
Mlofsi	Kbvzeo
Mlofdn	Kbvzdi
Mlofdg	Kbvzdr
Mlofdd	Kbvzdd
Mlofda	Kbvzdt
Mlofdl	Kbvzdm
Mlofdi	Kbvzdo
Mlofpn	Kbvzmi
Mlofpg	Kbvzmr
Mlofpd	Kbvzmd
Mlofpa	Kbvzmt
Mlofpl	Kbvzmm
Mlofpi	Kbvzmo
Mlonsn	Kbvsei
Mlonsg	Kbvser
Mlonsd	Kbvsed
Mlonsa	Kbvset
Mlonsl	Kbvsem
Mlonsi	Kbvseo
Mlondn	Kbvsdi
Mlondg	Kbvsdr
Mlondd	Kbvsdd
Mlonda	Kbvsdt
Mlondl	Kbvsdm
Mlondi	Kbvsdo
Mlonpn	Kbvsmi
Mlonpg	Kbvsmr
Mlonpd	Kbvsmd
Mlonpa	Kbvsmt
Mlonpl	Kbvsmm
Mlonpi	Kbvsmo
Mlpmsn	Kbzmei
Mlpmsnn	Kbzmein
Mlpmsny	Kbzmeid
Mlpmsg	Kbzmer
Mlpmsd	Kbzmed
Mlpmsa	Kbzmet
Mlpmsan	Kbzmetn
Mlpmsay	Kbzmetd
Mlpmsl	Kbzmem
Mlpmsi	Kbzmeo
Mlpmdn	Kbzmdi
Mlpmdg	Kbzmdr
Mlpmdd	Kbzmdd
Mlpmda	Kbzmdt
Mlpmdl	Kbzmdm
Mlpmdi	Kbzmdo
Mlpmpn	Kbzmmi
Mlpmpg	Kbzmmr
Mlpmpd	Kbzmmd
Mlpmpa	Kbzmmt
Mlpmpl	Kbzmmm
Mlpmpi	Kbzmmo
Mlpfsn	Kbzzei
Mlpfsg	Kbzzer
Mlpfsd	Kbzzed
Mlpfsa	Kbzzet
Mlpfsl	Kbzzem
Mlpfsi	Kbzzeo
Mlpfdn	Kbzzdi
Mlpfdg	Kbzzdr
Mlpfdd	Kbzzdd
Mlpfda	Kbzzdt
Mlpfdl	Kbzzdm
Mlpfdi	Kbzzdo
Mlpfpn	Kbzzmi
Mlpfpg	Kbzzmr
Mlpfpd	Kbzzmd
Mlpfpa	Kbzzmt
Mlpfpl	Kbzzmm
Mlpfpi	Kbzzmo
Mlpnsn	Kbzsei
Mlpnsg	Kbzser
Mlpnsd	Kbzsed
Mlpnsa	Kbzset
Mlpnsl	Kbzsem
Mlpnsi	Kbzseo
Mlpndn	Kbzsdi
Mlpndg	Kbzsdr
Mlpndd	Kbzsdd
Mlpnda	Kbzsdt
Mlpndl	Kbzsdm
Mlpndi	Kbzsdo
Mlpnpn	Kbzsmi
Mlpnpg	Kbzsmr
Mlpnpd	Kbzsmd
Mlpnpa	Kbzsmt
Mlpnpl	Kbzsmm
Mlpnpi	Kbzsmo
Mlsmsnn	Kbdmein
Mlsmsny	Kbdmeid
Mlsmsg	Kbdmer
Mlsmsd	Kbdmed
Mlsmsa	Kbdmet
Mlsmsan	Kbdmetn
Mlsmsay	Kbdmetd
Mlsmsl	Kbdmem
Mlsmsi	Kbdmeo
Mlsmdn	Kbdmdi
Mlsmdg	Kbdmdr
Mlsmdd	Kbdmdd
Mlsmda	Kbdmdt
Mlsmdl	Kbdmdm
Mlsmdi	Kbdmdo
Mlsmpn	Kbdmmi
Mlsmpg	Kbdmmr
Mlsmpd	Kbdmmd
Mlsmpa	Kbdmmt
Mlsmpl	Kbdmmm
Mlsmpi	Kbdmmo
Mlsfsn	Kbdzei
Mlsfsg	Kbdzer
Mlsfsd	Kbdzed
Mlsfsa	Kbdzet
Mlsfsl	Kbdzem
Mlsfsi	Kbdzeo
Mlsfdn	Kbdzdi
Mlsfdg	Kbdzdr
Mlsfdd	Kbdzdd
Mlsfda	Kbdzdt
Mlsfdl	Kbdzdm
Mlsfdi	Kbdzdo
Mlsfpn	Kbdzmi
Mlsfpg	Kbdzmr
Mlsfpd	Kbdzmd
Mlsfpa	Kbdzmt
Mlsfpl	Kbdzmm
Mlsfpi	Kbdzmo
Mlsnsn	Kbdsei
Mlsnsg	Kbdser
Mlsnsd	Kbdsed
Mlsnsa	Kbdset
Mlsnsl	Kbdsem
Mlsnsi	Kbdseo
Mlsndn	Kbdsdi
Mlsndg	Kbdsdr
Mlsndd	Kbdsdd
Mlsnda	Kbdsdt
Mlsndl	Kbdsdm
Mlsndi	Kbdsdo
Mlsnpn	Kbdsmi
Mlsnpg	Kbdsmr
Mlsnpd	Kbdsmd
Mlsnpa	Kbdsmt
Mlsnpl	Kbdsmm
Mlsnpi	Kbdsmo
Sn	Di
Sg	Dr
Sd	Dd
Sa	Dt
Sl	Dm
Si	Do
Cc	Vp
Cs	Vd
Q	L
I	M
Y	O
X	N
Xf	Nj
Xt	Nt
Xw	Nw
Xe	Ne
Xh	Nh
Xa	Na
Xp	Np
Z	U
